# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Semstrap
email: frank@magenta.dk
description: > # this means to ignore newlines until "baseurl:"
  Semstrap ("semantic bootstrap") is a layer of CSS that improves the look and feel of standard HTML elements.
baseurl: "/semstrap"
url: "http://iamfrank.github.io/"
github_username:  iamfrank

# Build settings
source:       ./
destination:  ./_site
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
sass_dir: ./_sass

markdown: kramdown

# Collections
collections:
- elements
- components

# SASS config
sass:
    style: compressed
