# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SemStrap docs
email: frank.thomsen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  SemStrap is a framework for styling good old semantic HTML. Kinda like Bootstrap but without the classes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iamfrank.github.io/semantic-strap" # the base hostname & protocol for your site
github_username:  iamfrank

# Build settings
source:       ./
destination:  ./_site
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes

markdown: kramdown

# Collections
collections:
- components
